FROM public.ecr.aws/lambda/provided:al2023.2023.11.18.01

FROM public.ecr.aws/lambda/python:3.11

# Install system packages, including build essentials
RUN yum update -y && \
    yum install -y \
    gzip \
    tar \
    curl \
    wget 

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.handler" ]