FROM public.ecr.aws/lambda/provided:al2023.2023.11.18.01

FROM public.ecr.aws/lambda/python:3.11

# Install system packages, including build essentials
RUN yum update -y && \
    yum install -y \
    gzip \
    tar \
    curl \
    wget \
    gcc \
    make \
    libc-dev \
    libffi-dev \
    libxslt-dev \
    zlib1g-dev \
    libXinerama \
    libXext \
    libXrender \
    libGL \
    libcairo2 \
    cairo \
    cups-libs
 
# Download and install LibreOffice
        
RUN wget https://mirror.mci-1.serverforge.org/tdf/libreoffice/stable/7.6.3/rpm/x86_64/LibreOffice_7.6.3_Linux_x86-64_rpm.tar.gz && \
    tar -xvf LibreOffice_7.6.3_Linux_x86-64_rpm.tar.gz && \
    cd LibreOffice_7.6.3.2_Linux_x86-64_rpm/RPMS/ && \
    yum localinstall -y *.rpm

ENV PATH="${PATH}:/opt/libreoffice7.6/program/"

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code
COPY lambda_function.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "lambda_function.handler" ]